# Generated by Django 2.1.7 on 2019-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='addr',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
