# Generated by Django 2.1.7 on 2019-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('paw', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
