# Generated by Django 2.1.7 on 2019-04-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='paw',
            new_name='pwd',
        ),
    ]
