# Generated by Django 2.1.7 on 2019-04-15 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='images/goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gunit', models.CharField(default='500g', max_length=20)),
                ('gclick', models.IntegerField()),
                ('gsummary', models.CharField(max_length=200)),
                ('gkucun', models.IntegerField()),
                ('gcontent', tinymce.models.HTMLField()),
                ('gjudgement', models.CharField(max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
                ('goodsadv', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goodsinfo',
            },
            managers=[
                ('goodsobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'typeinfo',
            },
            managers=[
                ('typeobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homegoods.TypeInfo'),
        ),
    ]
