# Generated by Django 2.1.7 on 2019-04-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carts',
            table='carts',
        ),
    ]
