# Generated by Django 2.1.7 on 2019-04-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190417_1356'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartsinfo',
            table='cartsinfo',
        ),
    ]
